#!/usr/bin/env bash
# Display Holberton school 10 times but with a while

x=1
while [ $x -le 10 ]
do
    echo "Holberton School"
    if [ $x -eq 9 ]
    then
        echo "Hi"
    fi
    x=$((x+1))
done
